version: '3'

services:
  backend:
    container_name: magnisa-backend
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./configs/.env
    volumes:
      - .:/magnisa/
      - /magnisa/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    entrypoint: [ "./start.sh" ]
  postgres:
    image: postgres:14-alpine
    container_name: magnisa-postgres
    environment:
      POSTGRES_PASSWORD: test123
      POSTGRES_USER: myPostgres
      POSTGRES_DB: magnisa
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
